=== chickenroyal/chickenroyal.github.io/gigs/gigs_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "eventType": {
        "type": "string",
        "enum": ["show", "festival"],
        "description": "Type of music event"
      },
      "eventName": {
        "type": "string",
        "description": "Name of the music event"
      },
      "date": {
        "type": "string",
        "format": "date",
        "description": "Date of the event"
      },
      "endDate": {
        "type": "string",
        "format": "date",
        "description": "End date of the event"
      },
      "location": {
        "type": "object",
        "properties": {
          "venue": {
            "type": "string",
            "description": "Venue where the event is held"
          },
          "city": {
            "type": "string",
            "description": "City where the event is taking place"
          },
          "country": {
            "type": "string",
            "description": "Country where the event is happening"
          }
        },
        "required": ["venue", "city", "country"]
      },
      "artists": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Name of the artist"
            },
            "role": {
              "type": "string",
              "enum": ["headliner", "support"],
              "description": "Role of the artist in the event"
            }
          },
          "required": ["name", "role"]
        },
        "description": "List of artists performing at the event"
      },
      "ticket": {
        "type": "object",
        "description": "Information about ticket types and pricing",
        "properties": {
          "ticketType": {
            "type": "string",
            "description": "Type of ticket (e.g., General Admission, Seated, VIP, etc.)"
          },
          "price": {
            "type": "number",
            "description": "Price of the ticket"
          },
          "currency": {
            "type": "string",
            "description": "Currency for the ticket price (e.g., GBP, EUR, CAD)"
          }
        },
        "required": ["ticketType", "price", "currency"]
      }
    },
    "required": ["eventType", "date", "location", "ticket"]
  }
}

=== chickenroyal/chickenroyal.github.io/gigs/gigs.json
[
  {
    "eventType": "show",
    "eventName": "",
    "date": "2004-02-22T19:30:00Z",
    "location": {
      "venue": "Northumbria University",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "[spunge]",
        "role": "headliner"
      },
      {
        "name": "Graveltrap",
        "role": "support"
      },
      {
        "name": "Never Heard of It",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 8,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2004-03-03T19:30:00Z",
    "location": {
      "venue": "Newcastle University",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "CKY",
        "role": "headliner"
      },
      {
        "name": "Fireball Ministry",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 10,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2004-06-09T19:30:00Z",
    "location": {
      "venue": "Northumbria University",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Jet",
        "role": "headliner"
      },
      {
        "name": "10,000 Things",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 12.50,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2004-12-02T19:00:00Z",
    "location": {
      "venue": "Metro Radio Arena",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "blink-182",
        "role": "headliner"
      },
      {
        "name": "Sugarcult",
        "role": "support"
      },
      {
        "name": "The Kinison",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 20,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2005-02-08T19:00:00Z",
    "location": {
      "venue": "Metro Radio Arena",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Green Day",
        "role": "headliner"
      },
      {
        "name": "New Found Glory",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 22.50,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2005-03-03T19:30:00Z",
    "location": {
      "venue": "Newcastle University",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Dropkick Murphys",
        "role": "headliner"
      },
      {
        "name": "The Bouncing Souls",
        "role": "support"
      },
      {
        "name": "The God Awfuls",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 12.50,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2005-04-19T19:00:00Z",
    "location": {
      "venue": "Northumbria University",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "The Hives",
        "role": "headliner"
      },
      {
        "name": "Blues Explosion",
        "role": "support"
      },
      {
        "name": "The D4",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 15,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2005-11-13T19:00:00Z",
    "location": {
      "venue": "Carling Academy Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Bloodhound Gang",
        "role": "headliner"
      },
      {
        "name": "Electric Eel Shock",
        "role": "support"
      },
      {
        "name": "The Lucky Nine",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 13.50,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2005-11-18T19:00:00Z",
    "location": {
      "venue": "Carling Academy Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Alkaline Trio",
        "role": "headliner"
      },
      {
        "name": "Mike Park",
        "role": "support"
      },
      {
        "name": "Sunshine",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 14,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2006-01-23T19:00:00Z",
    "location": {
      "venue": "Carling Academy Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Bullet for My Valentine",
        "role": "headliner"
      },
      {
        "name": "Aiden",
        "role": "support"
      },
      {
        "name": "Hawthorne Heights",
        "role": "support"
      },
      {
        "name": "Still Remains",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 14,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2006-03-19T19:00:00Z",
    "location": {
      "venue": "Newcastle University",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Fightstar",
        "role": "headliner"
      },
      {
        "name": "Brigade",
        "role": "support"
      },
      {
        "name": "Last Days of April",
        "role": "support"
      },
      {
        "name": "Reuben",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 12,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2006-04-24T19:00:00Z",
    "location": {
      "venue": "Carling Academy Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "HIM",
        "role": "headliner"
      },
      {
        "name": "Anathema",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 18,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2006-07-06T19:00:00Z",
    "location": {
      "venue": "Carling Academy Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Lostprophets",
        "role": "headliner"
      },
      {
        "name": "Kids in Glass Houses",
        "role": "support"
      },
      {
        "name": "The Blackout",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 16,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2006-09-21T19:00:00Z",
    "location": {
      "venue": "Newcastle University",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Motion City Soundtrack",
        "role": "headliner"
      },
      {
        "name": "OK Go",
        "role": "support"
      },
      {
        "name": "The Matches",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 10,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2006-09-28T19:00:00Z",
    "location": {
      "venue": "Carling Academy 2 Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Zebrahead",
        "role": "headliner"
      },
      {
        "name": "Takota",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 7.50,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2006-11-09T19:00:00Z",
    "location": {
      "venue": "Carling Academy Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Less Than Jake",
        "role": "headliner"
      },
      {
        "name": "Dropkick Murphys",
        "role": "support"
      },
      {
        "name": "Billy No Mates",
        "role": "support"
      },
      {
        "name": "The Living End",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 17.50,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2006-11-13T19:00:00Z",
    "location": {
      "venue": "Carling Academy Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Rancid",
        "role": "headliner"
      },
      {
        "name": "Holy Racket",
        "role": "support"
      },
      {
        "name": "The Unseen",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
      "price": 14,
      "currency": "£"
    }
  },
  {
    "eventType": "show",
    "eventName": "",
    "date": "2007-01-03T19:00:00Z",
    "location": {
      "venue": "Carling Academy Newcastle",
      "city": "Newcastle",
      "country": "England"
    },
    "artists": [
      {
        "name": "Bullet for My Valentine",
        "role": "headliner"
      },
      {
        "name": "As I Lay Dying",
        "role": "support"
      },
      {
        "name": "Gallows",
        "role": "support"
      }
    ],
    "ticket": {
      "ticketType": "General Admission",
